### ISSUE TITLE
Weird behavior with contrived invalid crate names

### ISSUE THREAD

**Issue by Gaelan** [theduke/crates-io-api#44]
```rust
let client = SyncClient::new("Testing crates_io_api crate; gbs@canishe.com", Duration::from_secs(1)).unwrap();
// imagine the crate name here was user input
dbg!(client.get_crate("rand/downloads"));
```

results in 

```
[src/main.rs:7] client.get_crate("rand/downloads") = Err(
    Http(
        reqwest::Error {
            kind: Decode,
            source: Error("missing field `categories`", line: 1, column: 28728),
        },
    ),
)
```

What's happening here is that `crates-io-api` is requesting `https://crates.io/api/v1/rand/downloads`, but trying to parse it as the normal crate metadata, resulting in an error. The error we get here isn't ideal: it implies that something is wrong internally (either with the client or with crates.io), when really the input was invalid. It'd be nice to detect this case, and respond with an error along the lines of "not found" or "invalid crate name".

**Comment by theduke** [comment]
This was triple weird for a few reasons:

* The crate name wasn't path encoded before, so the URL was just plain wrong for crate names with a slash
  => now happens
* The client didn't actually handle errors returned by api in the `errors: ...` field.
  => also now implemented
* The API actually returns a really weird error (`semantic version mismatch` or some such) instead of a 404
  => mitigated by doing a manual check for crate names with `/` and just giving a 404
